export interface Wilaya {
  code: number;
  name: string;
}

export const WILAYAS: Wilaya[] = [
  { code: 1, name: "Adrar" },
  { code: 2, name: "Chlef" },
  { code: 3, name: "Laghouat" },
  { code: 4, name: "Oum El Bouaghi" },
  { code: 5, name: "Batna" },
  { code: 6, name: "Béjaïa" },
  { code: 7, name: "Biskra" },
  { code: 8, name: "Béchar" },
  { code: 9, name: "Blida" },
  { code: 10, name: "Bouira" },
  { code: 11, name: "Tamanrasset" },
  { code: 12, name: "Tébessa" },
  { code: 13, name: "Tlemcen" },
  { code: 14, name: "Tiaret" },
  { code: 15, name: "Tizi Ouzou" },
  { code: 16, name: "Alger" },
  { code: 17, name: "Djelfa" },
  { code: 18, name: "Jijel" },
  { code: 19, name: "Sétif" },
  { code: 20, name: "Saïda" },
  { code: 21, name: "Skikda" },
  { code: 22, name: "Sidi Bel Abbès" },
  { code: 23, name: "Annaba" },
  { code: 24, name: "Guelma" },
  { code: 25, name: "Constantine" },
  { code: 26, name: "Médéa" },
  { code: 27, name: "Mostaganem" },
  { code: 28, name: "M'Sila" },
  { code: 29, name: "Mascara" },
  { code: 30, name: "Ouargla" },
  { code: 31, name: "Oran" },
  { code: 32, name: "El Bayadh" },
  { code: 33, name: "Illizi" },
  { code: 34, name: "Bordj Bou Arréridj" },
  { code: 35, name: "Boumerdès" },
  { code: 36, name: "El Tarf" },
  { code: 37, name: "Tindouf" },
  { code: 38, name: "Tissemsilt" },
  { code: 39, name: "El Oued" },
  { code: 40, name: "Khenchela" },
  { code: 41, name: "Souk Ahras" },
  { code: 42, name: "Tipaza" },
  { code: 43, name: "Mila" },
  { code: 44, name: "Aïn Defla" },
  { code: 45, name: "Naâma" },
  { code: 46, name: "Aïn Témouchent" },
  { code: 47, name: "Ghardaïa" },
  { code: 48, name: "Relizane" },
  { code: 49, name: "El M'Ghair" },
  { code: 50, name: "El Meniaa" },
  { code: 51, name: "Ouled Djellal" },
  { code: 52, name: "Bordj Badji Mokhtar" },
  { code: 53, name: "Béni Abbès" },
  { code: 54, name: "Timimoun" },
  { code: 55, name: "Touggourt" },
  { code: 56, name: "Djanet" },
  { code: 57, name: "In Salah" },
  { code: 58, name: "In Guezzam" },
];

export const WILAYA_COMMUNES: Record<number, string[]> = {
  1: [
    "Adrar",
    "Reggane",
    "In Salah",
    "Timimoun",
    "Aoulef",
    "Tsabit",
    "Fenoughil",
    "Zaouiet Kounta",
    "Bordj Badji Mokhtar",
    "Tamest",
    "Tit",
    "Ksar Kaddour",
    "In Zghmir",
    "Sali",
    "Talmine",
    "Charouine",
    "Ouled Ahmed Timmi",
    "Bouda",
    "Metarfa",
    "Tamantit",
  ],
  2: [
    "Chlef",
    "Ténès",
    "El Karimia",
    "Taougrit",
    "Beni Haoua",
    "Boukadir",
    "Oued Fodda",
    "El Marsa",
    "Ain Merane",
    "Ouled Fares",
    "Chettia",
    "Oum Drou",
    "Beni Rached",
    "Abou El Hassan",
    "Zeboudja",
    "Breira",
    "El Hadjadj",
    "Moussadek",
    "Sobha",
    "Harchoun",
  ],
  3: [
    "Laghouat",
    "Aflou",
    "Ksar El Hirane",
    "Hassi R'Mel",
    "Ain Madhi",
    "El Ghicha",
    "Brida",
    "Tadjmout",
    "Sidi Makhlouf",
    "Hassi Delaa",
    "Oued Morra",
    "Gueltat Sidi Saad",
    "El Haouaita",
    "Ain Sidi Ali",
    "Tadjrouna",
    "Hadj Mechri",
  ],
  4: [
    "Oum El Bouaghi",
    "Ain Beida",
    "Ain M'lila",
    "Ksar Sbahi",
    "Sigus",
    "Ain Fakroun",
    "Meskiana",
    "Dhalaa",
    "Ain Babouche",
    "Ain Kercha",
    "Fkirina",
    "Souk Naamane",
    "Ain Zitoun",
    "Behir Chergui",
    "Hanchir Toumghani",
  ],
  5: [
    "Batna",
    "Barika",
    "Aïn Touta",
    "N'Gaous",
    "Merouana",
    "Tazoult",
    "Arris",
    "Timgad",
    "Seggana",
    "Menaa",
    "Ain Djasser",
    "El Madher",
    "Ichemoul",
    "Tkout",
    "Chemora",
    "Oued Chaaba",
    "Ras El Aioun",
    "Ain Yagout",
    "Fesdis",
    "Talkhamt",
  ],
  6: [
    "Béjaïa",
    "Akbou",
    "Sidi Aich",
    "Amizour",
    "El Kseur",
    "Kherrata",
    "Tichy",
    "Aokas",
    "Seddouk",
    "Tazmalt",
    "Ifri Ouzellaguen",
    "Ighil Ali",
    "Darguina",
    "Souk El Tenine",
    "Adekar",
    "Barbacha",
    "Toudja",
    "Feraoun",
    "Chemini",
    "Tibane",
  ],
  7: [
    "Biskra",
    "Tolga",
    "Ouled Djellal",
    "Sidi Okba",
    "M'Chounèche",
    "Zeribet El Oued",
    "Sidi Khaled",
    "El Kantara",
    "Foughala",
    "Djemorah",
    "El Outaya",
    "Lioua",
    "Ourlal",
    "Serkou",
    "Doucen",
    "Ain Naga",
    "Branis",
    "Chaiba",
  ],
  8: [
    "Béchar",
    "Abadla",
    "Beni Ounif",
    "Kenadsa",
    "Taghit",
    "Igli",
    "Tabelbala",
    "Lahmar",
    "Beni Abbès",
    "Meridja",
    "Mechraa Houari",
    "Mougheul",
    "Kissal",
    "El Ouata",
    "Boukaïs",
  ],
  9: [
    "Blida",
    "Boufarik",
    "Bougara",
    "Mouzaia",
    "El Affroun",
    "Ouled Yaïch",
    "Chréa",
    "Beni Mered",
    "Chiffa",
    "Oued El Alleug",
    "Meftah",
    "Djebabra",
    "Soumaa",
    "Bouinan",
    "Larbaa",
    "Ben Khelil",
    "Hammam Melouane",
    "Oued Djer",
    "Beni Tamou",
    "Guerrouaou",
    "Chabet El Ameur",
    "Ain Romana",
    "El Khabouzia",
    "Mghaira",
    "Ouled Selama",
  ],
  10: [
    "Bouira",
    "Lakhdaria",
    "Sour El Ghozlane",
    "M'Chedallah",
    "Bechloul",
    "El Hachimia",
    "Kadiria",
    "Ain Bessem",
    "Bordj Okhriss",
    "Hammam Dalaa",
    "Aghbalou",
    "Aomar",
    "Bir Ghbalou",
    "El Adjiba",
    "El Achir",
    "Dechmia",
    "Taghzout",
    "Bouderbala",
    "Haizer",
    "El Okassa",
  ],
  11: [
    "Tamanrasset",
    "In Guezzam",
    "Abalessa",
    "In Amguel",
    "Ideles",
    "Tazrouk",
    "Tin Zaouatine",
    "In Salah",
  ],
  12: [
    "Tébessa",
    "Bir El Ater",
    "Cheria",
    "El Aouinet",
    "El Malabiod",
    "El Kouif",
    "Morsott",
    "Negrine",
    "Ouenza",
    "El Ogla",
    "Bekkaria",
    "Boulhaf Dyr",
    "Hammamet",
    "El Mezeraa",
    "Boukhzam",
    "Stah Guentis",
    "Ain Zerga",
  ],
  13: [
    "Tlemcen",
    "Maghnia",
    "Ghazaouet",
    "Remchi",
    "Nedroma",
    "Sebdou",
    "Beni Saf",
    "Hennaya",
    "Chetouane",
    "Mansourah",
    "Chouachi",
    "Ain Fezza",
    "Ain Youcef",
    "Bab El Assa",
    "Ouled Mimoun",
    "Sidi Djillali",
    "Fellaoucene",
    "Ain Nehala",
    "Honaine",
  ],
  14: [
    "Tiaret",
    "Frenda",
    "Ksar Chellala",
    "Sougueur",
    "Ain Deheb",
    "Mahdia",
    "Rahouia",
    "Oued Lilli",
    "Mechraa Sfa",
    "Ain Bouchekif",
    "Dahmouni",
    "Hamadia",
    "Meghila",
    "Medroussa",
    "Ain El Hadid",
    "Rechaiga",
    "Sidi Hosni",
    "Nadorah",
  ],
  15: [
    "Tizi Ouzou",
    "Azazga",
    "Aïn El Hammam",
    "Larbaâ Nath Irathen",
    "Draâ Ben Khedda",
    "Draâ El Mizan",
    "Boghni",
    "Ouaguenoun",
    "Mekla",
    "Tigzirt",
    "Ouadhias",
    "Beni Douala",
    "Beni Yenni",
    "Tirmitine",
    "Maatkas",
    "Iferhounene",
    "Bouzguene",
    "Iflissen",
    "Azeffoun",
    "Makouda",
    "Freha",
    "Tadmaya",
  ],
  16: [
    "Alger-Centre",
    "Sidi M'Hamed",
    "El Madania",
    "Belouizdad",
    "Bab El Oued",
    "Bologhine",
    "Oued Smar",
    "Bourouba",
    "Hussein Dey",
    "Kouba",
    "Bachdjerrah",
    "El Harrach",
    "Baraki",
    "Oued Koriche",
    "Bir Mourad Raïs",
    "El Biar",
    "Bouzareah",
    "Birkhadem",
    "El Mouradia",
    "Hydra",
    "Ben Aknoun",
    "Dely Ibrahim",
    "Bab Ezzouar",
    "Dar El Beïda",
    "Rouiba",
    "Aïn Taya",
    "Bordj El Kiffan",
    "El Mohammadia",
    "Reghaia",
    "Aïn Benian",
    "Staoueli",
    "Zeralda",
    "Cheraga",
    "Ouled Fayet",
    "El Achour",
    "Draria",
    "Douera",
    "Baba Hassen",
    "Khraicia",
    "Saoula",
    "Tessala El Merdja",
    "Heraoua",
    "Mohammadia",
  ],
  17: [
    "Djelfa",
    "Aïn Oussera",
    "Messaad",
    "Hassi Bahbah",
    "Charef",
    "M'Liliha",
    "Dar Chioukh",
    "Had Sahary",
    "El Idrissia",
    "Ain El Ibel",
    "Birine",
    "Hassi El Euch",
    "Faidh El Botma",
    "Moudjbara",
    "Sed Rahal",
    "El Guedid",
    "Mekhadma",
    "Zaafrane",
    "Ain Fekan",
  ],
  18: [
    "Jijel",
    "El Milia",
    "Taher",
    "Chekfa",
    "Sidi Marouf",
    "Texenna",
    "Ziama Mansouriah",
    "El Ancer",
    "Settara",
    "El Aouana",
    "Oudjana",
    "Kaous",
    "Selma Benziada",
    "Djimla",
    "Sidi Abdelaziz",
    "El Guelta",
    "Ouled Yahia Khadrouche",
  ],
  19: [
    "Sétif",
    "El Eulma",
    "Aïn Oulmene",
    "Aïn Arnat",
    "Bougaa",
    "Aïn Azel",
    "Beni Aziz",
    "Guenzet",
    "Maoklane",
    "Hammam Soukhna",
    "Amoucha",
    "Babor",
    "Bouandas",
    "Ksar El Abtal",
    "Beni Ourtilane",
    "Djemila",
    "Ain El Kebira",
    "El Ouricia",
  ],
  20: [
    "Saïda",
    "Ain El Hadjar",
    "Youb",
    "Ouled Brahim",
    "Hassasna",
    "Sidi Boubekeur",
    "El Hassasna",
    "Moulay Larbi",
    "Doui Thabet",
    "Ain Soltane",
    "Sidi Amar",
    "Tircine",
  ],
  21: [
    "Skikda",
    "Azzaba",
    "Ain Kechra",
    "Collo",
    "El Harrouch",
    "Ramdane Djamel",
    "Tamalous",
    "Zitouna",
    "Oued Z'hor",
    "Ben Azzouz",
    "El Hadaiek",
    "Sidi Mezghiche",
    "Salah Bouchaour",
    "Oum Toub",
    "Zerizer",
    "Bouchetata",
    "Hamadi Krouma",
  ],
  22: [
    "Sidi Bel Abbès",
    "Telagh",
    "Ain El Berd",
    "Ben Badis",
    "Sfisef",
    "Tessala",
    "Merine",
    "Mostefa Ben Brahim",
    "Ras El Ma",
    "Tenira",
    "Sidi Ali Boussidi",
    "Sidi Lahcene",
    "Makedra",
    "Sidi Brahim",
    "Hassi Zahana",
    "Ain Thrid",
    "Lamtar",
    "Sidi Djillali",
  ],
  23: [
    "Annaba",
    "El Bouni",
    "El Hadjar",
    "Berrahal",
    "Seraidi",
    "Ain El Berda",
    "Cheurfa",
    "Oued El Aneb",
    "Chetaibi",
  ],
  24: [
    "Guelma",
    "Oued Zenati",
    "Bouchegouf",
    "Hammam Debagh",
    "Héliopolis",
    "Ain Makhlouf",
    "Houari Boumediene",
    "Khezara",
    "Nechmaya",
    "Ain Sandel",
    "Belkheir",
    "Djebala Khemissi",
    "Sellaoua Announa",
    "Hammam N'Bails",
    "Medjez Amar",
    "Oued Cheham",
  ],
  25: [
    "Constantine",
    "El Khroub",
    "Aïn Smara",
    "Hamma Bouziane",
    "Didouche Mourad",
    "Zighoud Youcef",
    "Ibn Ziad",
    "Ali Mendjeli",
    "Ain Abid",
    "Ouled Rahmoune",
    "Messaoud Boudjeriou",
    "Beni Hamidane",
  ],
  26: [
    "Médéa",
    "Berrouaghia",
    "Ksar El Boukhari",
    "Tablat",
    "Ain Boucif",
    "Beni Slimane",
    "El Omaria",
    "Ouamri",
    "Chahbounia",
    "Souagui",
    "Si Mahdjoub",
    "Ouled Derraji",
    "Chellalet El Adhaoura",
    "Damiat",
    "Seghouane",
    "Mihoub",
    "Ouzera",
    "Tamesguida",
  ],
  27: [
    "Mostaganem",
    "Ain Nouissy",
    "Sidi Ali",
    "Ain Tedles",
    "Hassi Maameche",
    "Kheir Eddine",
    "Sidi Lakhdar",
    "Achaacha",
    "Mansourah",
    "Bouguirat",
    "Mesra",
    "Fornaka",
    "Hadjadj",
    "Sidi Maamar",
    "Ouled Maalah",
    "Mazagran",
  ],
  28: [
    "M'Sila",
    "Bou Saada",
    "Ain El Melh",
    "Sidi Aissa",
    "Hammam Dalaa",
    "Magra",
    "Khoubana",
    "Ain El Hadjel",
    "Chellal",
    "Ouled Sidi Brahim",
    "Ben Srour",
    "Medjedel",
    "M'Tarfa",
    "Berhoum",
    "Ouled Derradj",
    "Benzouh",
    "Djebel Messaad",
  ],
  29: [
    "Mascara",
    "Sig",
    "Mohammadia",
    "Ain Fares",
    "Tighennif",
    "Bou Hanifia",
    "Hachem",
    "El Bordj",
    "Ain Fekkan",
    "Oued Taria",
    "Oued El Abtal",
    "Ghriss",
    "Zahana",
    "Froha",
    "Maoussa",
    "Khalouia",
    "Matemore",
  ],
  30: [
    "Ouargla",
    "Hassi Messaoud",
    "Touggourt",
    "Temacine",
    "Megarine",
    "Taibet",
    "El Alia",
    "El Hadjira",
    "Rouissat",
    "N'Goussa",
    "Sidi Khouiled",
    "Ain Beida",
    "El Borma",
    "Zaouia El Abidia",
  ],
  31: [
    "Oran",
    "Bir El Djir",
    "Es Senia",
    "Arzew",
    "Bethioua",
    "Gdyel",
    "Hassi Bounif",
    "Oued Tlelat",
    "Ain Turk",
    "Mers El Kébir",
    "Boutlelis",
    "Ain El Kerma",
    "Bousfer",
    "El Braya",
    "Hassi Ben Okba",
    "Hassi Mefsoukh",
    "El Kerma",
    "Sidi Chahmi",
    "Ben Freha",
    "Misserghin",
    "Bou Sfer",
    "Ain El Bya",
  ],
  32: [
    "El Bayadh",
    "Bougtob",
    "Brezina",
    "Labiodh Sidi Cheikh",
    "Ain El Orak",
    "Chellala",
    "Rogassa",
    "Boualem",
    "Ghassoul",
    "Bnoud",
    "El Mehara",
    "Kef El Ahmar",
    "Sidi Slimane",
    "Sidi Ameur",
    "Stidia",
  ],
  33: [
    "Illizi",
    "Djanet",
    "In Amenas",
    "Debdeb",
    "Bordj Omar Driss",
  ],
  34: [
    "Bordj Bou Arréridj",
    "Ras El Oued",
    "Bir Kasdali",
    "Mansourah",
    "Medjana",
    "El Achir",
    "Djaafra",
    "Ain Taghrout",
    "Bordj Ghedir",
    "Bordj Zemoura",
    "Hasnaoua",
    "El Hamadia",
    "Sidi Embarek",
    "Taglait",
    "Teniet En Nasr",
  ],
  35: [
    "Boumerdès",
    "Bordj Menaïel",
    "Thenia",
    "Tidjelabine",
    "Hammedi",
    "Isser",
    "Si Mustapha",
    "Naciria",
    "Ouled Moussa",
    "Corso",
    "Baghlia",
    "Timezrit",
    "Dellys",
    "Boudouaou",
    "Khemis El Khechna",
    "Ouled Aissa",
    "Zemmouri",
    "Larbatache",
    "Tadjena",
    "Afir",
    "Beni Amrane",
    "Souk El Had",
  ],
  36: [
    "El Tarf",
    "El Kala",
    "Bouhadjar",
    "Ben M'Hidi",
    "Bouteldja",
    "Ain El Assel",
    "Besbes",
    "Dréan",
    "Boumathe",
    "Ain Kerma",
    "Chihani",
    "Echatt",
    "Lac des Oiseaux",
    "Zerizer",
    "Oued Zitoun",
    "Berrihane",
    "Zitouna",
  ],
  37: [
    "Tindouf",
    "Oum El Assel",
  ],
  38: [
    "Tissemsilt",
    "Theniet El Had",
    "Bordj Bou Naama",
    "Khemisti",
    "Layoune",
    "Ammari",
    "Bordj Emir Abdelkader",
    "Lazharia",
    "Ouled Bessam",
    "Lardjem",
    "Maacem",
    "Sidi Lantri",
    "Beni Chaib",
    "Beni Lahcene",
    "Tamalaht",
    "Sidi Slimane",
  ],
  39: [
    "El Oued",
    "Guemar",
    "Robbah",
    "Debila",
    "Hassani Abdelkrim",
    "Bayadha",
    "Djamaa",
    "Oum Touyour",
    "Kouinine",
    "Reguiba",
    "Magrane",
    "Oued El Alenda",
    "N'Sigha",
    "Still",
    "El Ogla",
    "Hassi Khalifa",
    "Trifaoui",
    "Hassi Ben Abdellah",
    "Ourmas",
    "El M'Ghair",
  ],
  40: [
    "Khenchela",
    "Kaïs",
    "Baghai",
    "Chechar",
    "El Hamma",
    "Bouhmama",
    "Ain Touila",
    "Tamza",
    "Ouled Rechache",
    "El Oueldja",
    "Babar",
    "M'Sara",
    "Ensigha",
    "Taouzianat",
    "Remila",
  ],
  41: [
    "Souk Ahras",
    "Sedrata",
    "M'Daourouch",
    "Taoura",
    "Ain Zana",
    "Ouled Driss",
    "Mechroha",
    "Bir Bouhouche",
    "Haddada",
    "Oum El Adhaim",
    "Zaarouria",
    "Khemissa",
    "Terraguelt",
    "Oued Keberit",
    "Merahna",
  ],
  42: [
    "Tipaza",
    "Koléa",
    "Hadjout",
    "Cherchell",
    "Bou Ismaïl",
    "Fouka",
    "Ahmer El Ain",
    "Gouraya",
    "Damous",
    "Menaceur",
    "Sidi Amar",
    "Chaïba",
    "Larhat",
    "Sidi Rached",
    "Messelmoun",
    "Ain Tagourait",
    "Bou Haroun",
    "Nador",
    "Attatba",
  ],
  43: [
    "Mila",
    "Ferdjioua",
    "Chelghoum Laïd",
    "Grarem Gouga",
    "Oued Athmenia",
    "Rouached",
    "Teleghma",
    "Ain Beida Harriche",
    "Tassadane Haddada",
    "Oued Seguen",
    "Sidi Merouane",
    "Bouhatem",
    "Benyahia Abderrahmane",
    "Terrai Bainen",
    "Ain Mellouk",
    "Tiberguent",
    "Amira Arras",
  ],
  44: [
    "Aïn Defla",
    "Khémis Miliana",
    "Miliana",
    "Djelida",
    "Hammam Righa",
    "El Abadia",
    "Rouina",
    "Zeddine",
    "Ain Lechiakh",
    "Bourached",
    "Djendel",
    "El Attaf",
    "Ain Benian",
    "Ain Soltane",
    "Bordj Emir Khaled",
    "Ain Bouyahia",
    "Tiberkanine",
    "El Amra",
    "Mekhatria",
    "Bathia",
  ],
  45: [
    "Naâma",
    "Mecheria",
    "Ain Sefra",
    "Tiout",
    "Sfissifa",
    "Moghrar",
    "Djenien Bourezg",
    "Asla",
    "Kasdir",
    "Ain Ben Khelil",
  ],
  46: [
    "Aïn Témouchent",
    "Hammam Bou Hadjar",
    "Beni Saf",
    "El Amria",
    "El Malah",
    "Ain Kihal",
    "Oulhaça El Gheraba",
    "Ain El Arbaa",
    "Aghlal",
    "El Ouahda",
    "Hassi El Ghella",
    "Sidi Ben Adda",
    "Oued Berkeche",
    "Sidi Safi",
    "Ain Tolba",
    "Chentouf",
  ],
  47: [
    "Ghardaïa",
    "Metlili",
    "El Guerrara",
    "Berriane",
    "Dhayet Bendhahoua",
    "Zelfana",
    "Bounoura",
    "El Atteuf",
    "Mansoura",
    "Hassi Gara",
    "Sebseb",
    "El Meniaa",
  ],
  48: [
    "Relizane",
    "Oued Rhiou",
    "Mazouna",
    "Yellel",
    "Ain Tarek",
    "Mendes",
    "Sidi M'Hamed Ben Ali",
    "Djidiouia",
    "Ammi Moussa",
    "Zemmoura",
    "El Matmar",
    "Had Echkalla",
    "Sidi Khettab",
    "El Hamadna",
    "Beni Dergoun",
    "Oued Essalem",
    "El Guettar",
    "Sidi Abdeldjebar",
    "Ain Rahma",
    "Bendaoud",
  ],
  49: [
    "El M'Ghair",
    "Oum Touyour",
    "Still",
    "Sidi Khaled",
    "Djamaa",
  ],
  50: [
    "El Meniaa",
    "Hassi Gara",
    "Hassi Fehal",
  ],
  51: [
    "Ouled Djellal",
    "Sidi Khaled",
    "Chaiba",
    "Doucen",
    "Ras El Miaad",
  ],
  52: [
    "Bordj Badji Mokhtar",
    "Timiaouine",
    "In Zghmir",
  ],
  53: [
    "Béni Abbès",
    "Igli",
    "Tabelbala",
    "El Ouata",
    "Kerzaz",
    "Beni Ikhlef",
    "Ouled Khoudir",
    "Tamtert",
  ],
  54: [
    "Timimoun",
    "Charouine",
    "Ouled Said",
    "Tinerkouk",
    "Metarfa",
    "Deldoul",
    "Ksar Kaddour",
    "Ouled Ahmed Timmi",
    "Aougrout",
  ],
  55: [
    "Touggourt",
    "Temacine",
    "Megarine",
    "Taibet",
    "Zaouia El Abidia",
    "Blidet Amor",
    "Nezla",
    "Tebesbest",
    "El Hadjira",
  ],
  56: [
    "Djanet",
    "Bordj El Haoues",
    "In Abangarit",
  ],
  57: [
    "In Salah",
    "Foggaret Ezzaouia",
    "In Ghar",
    "Ain El Hadjel",
    "Hassi El Gara",
  ],
  58: [
    "In Guezzam",
    "Tin Zaouatine",
    "Assamaka",
  ],
};
